// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkgtnejqroqngtwecncs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrZ3RuZWpxcm9xbmd0d2VjbmNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3ODg0NTYsImV4cCI6MjA1MzM2NDQ1Nn0.BesKWWoMDzUfyNxFXg0doCr7ib5VYc_GQIS15acoE94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);